In [ ]:
import numpy as np
import pandas as pd
import os
import scipy.io
import matplotlib.pyplot as plt
from scipy import signal

In [ ]:
# pip install mne

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#Path which contains folders
PATH = "/content/drive/MyDrive/DatasetAttention/"

In [ ]:
files = os.listdir(PATH)
files

['eeg_record10.mat',
 'eeg_record11.mat',
 'eeg_record12.mat',
 'eeg_record13.mat',
 'eeg_record15.mat',
 'eeg_record14.mat',
 'eeg_record17.mat',
 'eeg_record16.mat',
 'eeg_record18.mat',
 'eeg_record19.mat',
 'eeg_record20.mat',
 'eeg_record22.mat',
 'eeg_record21.mat',
 'eeg_record23.mat',
 'eeg_record24.mat',
 'eeg_record25.mat',
 'eeg_record26.mat',
 'eeg_record27.mat',
 'eeg_record28.mat',
 'eeg_record29.mat',
 'eeg_record30.mat',
 'eeg_record31.mat',
 'eeg_record33.mat',
 'eeg_record32.mat',
 'eeg_record34.mat',
 'eeg_record9.mat',
 'eeg_record8.mat',
 'eeg_record7.mat',
 'eeg_record6.mat',
 'eeg_record5.mat',
 'eeg_record4.mat',
 'eeg_record3.mat',
 'eeg_record2.mat',
 'eeg_record1.mat']

In [ ]:
files.sort
files

['eeg_record10.mat',
 'eeg_record11.mat',
 'eeg_record12.mat',
 'eeg_record13.mat',
 'eeg_record15.mat',
 'eeg_record14.mat',
 'eeg_record17.mat',
 'eeg_record16.mat',
 'eeg_record18.mat',
 'eeg_record19.mat',
 'eeg_record20.mat',
 'eeg_record22.mat',
 'eeg_record21.mat',
 'eeg_record23.mat',
 'eeg_record24.mat',
 'eeg_record25.mat',
 'eeg_record26.mat',
 'eeg_record27.mat',
 'eeg_record28.mat',
 'eeg_record29.mat',
 'eeg_record30.mat',
 'eeg_record31.mat',
 'eeg_record33.mat',
 'eeg_record32.mat',
 'eeg_record34.mat',
 'eeg_record9.mat',
 'eeg_record8.mat',
 'eeg_record7.mat',
 'eeg_record6.mat',
 'eeg_record5.mat',
 'eeg_record4.mat',
 'eeg_record3.mat',
 'eeg_record2.mat',
 'eeg_record1.mat']

In [ ]:
from scipy.io import loadmat
import numpy as np
import pickle

Each participant took part in 7 experiments, performing at most one experiment per day. The first 2 experiments were used for habituation, and the last 5 trials were used for collecting the data. The first 7 experiments belong to Subject 1, the next 7 experiments belong to Subject 2, and go on. However, Subject 5 could not complete the last experiment. Therefore, there are 34 records in the dataset.


We have sampling frequency = 128Hz 
1st 10 minutes of data(t=0 min to t=10 min) is for "focussed" state 
2nd 10 minutes of data(t=10 min to t=20 min) is for "unfocussed" state 
Remaining data(t=20 min to onwards) is for "Drowsed" state


Therefore, 
"focused": row= 0
0
  to row= 128×10×60
128
×
10
×
60
  
"unfocused": row= 128×10×60
128
×
10
×
60
  to row= 128×20×60
128
×
20
×
60
  
"drowsed": row= 128×20×60
128
×
20
×
60
  to last row

Out of this 7 days or trials first 2 were for getting habitual with the process. Therefore we will consider only last five trials.

Subjects=5 
Trials=5 
(Note: subject 5 has only 4 trials)

labels = ['AF3','F7', 'F3','FC5','T7','P7','O1', 'O2','P8','T8', 'FC6','F4','F8','AF4']  # FP2 should really be AF4 (14 chs)

https://www.kaggle.com/datasets/inancigdem/eeg-data-for-mental-attention-state-detection/discussion/104782
the positions of the electrodes used in this work were F3-Fz-F4-C3-Cz-C4-T3-T4-T5-T6-Pz (11 channels)
And even in those, only the following channels have non-corrupt data:
[F7-F3-P7-O1-O2-P8-AF4] (7 channels) The acquired data from the 7 leads were identified by F3, F4, Fz, C3, C4, Cz, and Pz. 

Correct one is : 2,3,5,6,7,8,9,10,14==>F7,F3,T7,P7,O1,O2,P8,T8,AF4 (9 Chs) 5 and 10 were not used because they are reference channels
so [F7-F3-P7-O1-O2-P8-AF4] (7 channels) final.

https://www.kaggle.com/code/nitinsss/extracting-useful-data-from-the-mat-files/notebook

New author: new method: not used here: # look for https://github.com/FelixLin99/Kaggle_EDFMASD/blob/main/2_selectUsefulData.ipynb filter fn abd bandwaves; totally new method: https://github.com/FelixLin99/Kaggle_EDFMASD/blob/main/1_filterByMne.ipynb waves also

In [ ]:
files1 = ['eeg_record3.mat','eeg_record4.mat','eeg_record5.mat','eeg_record6.mat','eeg_record7.mat']

In [ ]:
files2 = ['eeg_record10.mat','eeg_record11.mat','eeg_record12.mat','eeg_record13.mat','eeg_record14.mat']

In [ ]:
files3 = ['eeg_record17.mat','eeg_record18.mat','eeg_record19.mat','eeg_record20.mat','eeg_record21.mat']

In [ ]:
files4 = ['eeg_record24.mat','eeg_record25.mat','eeg_record26.mat','eeg_record27.mat','eeg_record28.mat']

In [ ]:
files5 = ['eeg_record31.mat','eeg_record32.mat','eeg_record33.mat','eeg_record34.mat']

In [ ]:
print(files2)

['eeg_record10.mat', 'eeg_record11.mat', 'eeg_record12.mat', 'eeg_record13.mat', 'eeg_record14.mat']

In [ ]:
df1 = pd.DataFrame()
arrays_list = []
arraylistFileNames = []
arraylistFileNames2 = []
focusNos = 128*10*60

for file in files1:
    matFile = scipy.io.loadmat(PATH + file)
    matFile['o']['sampFreq'][0][0][0][0]
    array1 = matFile['o']['data'][0, 0][:, 3:17]

    # for array in arrays_list:
    arrays_list.append(array1)
    print(file)
    arraylistFileNames.append(file)
arraylistFileNames2
for array in arrays_list:
    df = pd.DataFrame(array)
    df['id'] = np.arange(df.shape[0])
    df['target'] = np.where(df['id'] < focusNos, 'Focus', 'Unfocus')
    df1 = df1.append(df)
df1 = df1.drop(columns = 'id')

eeg_record3.mat
eeg_record4.mat
eeg_record5.mat
eeg_record6.mat
eeg_record7.mat

In [ ]:
df1.shape

(1776340, 15)

In [ ]:
df1.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,target
398811,4431.282051,4070.256410,5089.743590,3821.538462,4031.282051,4362.564103,4373.846154,4138.974359,4232.307692,4314.871795,4144.615385,4291.794872,4336.410256,4158.974359,Unfocus
398812,4431.794872,4066.153846,5091.282051,3816.923077,4030.769231,4366.153846,4359.487179,4139.487179,4232.820513,4318.974359,4151.794872,4291.794872,4336.410256,4170.256410,Unfocus
398813,4432.307692,4053.846154,5088.717949,3817.948718,4029.230769,4360.512821,4335.384615,4126.666667,4230.769231,4317.948718,4151.282051,4291.794872,4335.897436,4168.717949,Unfocus
398814,4431.282051,4042.051282,5082.564103,3818.461538,4030.256410,4353.333333,4328.205128,4105.641026,4219.487179,4318.461538,4150.769231,4291.794872,4335.897436,4156.410256,Unfocus
398815,4430.769231,4030.769231,5075.897436,3816.923077,4030.256410,4346.153846,4320.000000,4093.333333,4210.256410,4319.487179,4153.846154,4291.794872,4336.410256,4150.256410,Unfocus

In [ ]:
df2 = pd.DataFrame()
arrays_list = []
arraylistFileNames = []
arraylistFileNames2 = []
focusNos = 128*10*60

for file in files2:
    matFile = scipy.io.loadmat(PATH + file)
    matFile['o']['sampFreq'][0][0][0][0]
    array1 = matFile['o']['data'][0, 0][:, 3:17]

    # for array in arrays_list:
    arrays_list.append(array1)
    print(file)
    arraylistFileNames.append(file)
arraylistFileNames2
for array in arrays_list:
    df = pd.DataFrame(array)
    df['id'] = np.arange(df.shape[0])
    df['target'] = np.where(df['id'] < focusNos, 'Focus', 'Unfocus')
    df2 = df1.append(df)
df2 = df2.drop(columns = 'id')

eeg_record10.mat
eeg_record11.mat
eeg_record12.mat
eeg_record13.mat
eeg_record14.mat

In [ ]:
df2.shape

(2121504, 15)

In [ ]:
df3 = pd.DataFrame()
arrays_list = []
arraylistFileNames = []
arraylistFileNames2 = []
focusNos = 128*10*60

for file in files3:
    matFile = scipy.io.loadmat(PATH + file)
    matFile['o']['sampFreq'][0][0][0][0]
    array1 = matFile['o']['data'][0, 0][:, 3:17]

    # for array in arrays_list:
    arrays_list.append(array1)
    print(file)
    arraylistFileNames.append(file)
arraylistFileNames2
for array in arrays_list:
    df = pd.DataFrame(array)
    df['id'] = np.arange(df.shape[0])
    df['target'] = np.where(df['id'] < focusNos, 'Focus', 'Unfocus')
    df3 = df3.append(df)
df3 = df3.drop(columns = 'id')
print(df3.shape)

eeg_record17.mat
eeg_record18.mat
eeg_record19.mat
eeg_record20.mat
eeg_record21.mat
(1872140, 15)

In [ ]:
df4 = pd.DataFrame()
arrays_list = []
arraylistFileNames = []
arraylistFileNames2 = []
focusNos = 128*10*60

for file in files4:
    matFile = scipy.io.loadmat(PATH + file)
    matFile['o']['sampFreq'][0][0][0][0]
    array1 = matFile['o']['data'][0, 0][:, 3:17]

    # for array in arrays_list:
    arrays_list.append(array1)
    print(file)
    arraylistFileNames.append(file)
arraylistFileNames2
for array in arrays_list:
    df = pd.DataFrame(array)
    df['id'] = np.arange(df.shape[0])
    df['target'] = np.where(df['id'] < focusNos, 'Focus', 'Unfocus')
    df4 = df4.append(df)
df4 = df4.drop(columns = 'id')
print(df4.shape)

eeg_record24.mat
eeg_record25.mat
eeg_record26.mat
eeg_record27.mat
eeg_record28.mat
(1701412, 15)

In [ ]:
df5 = pd.DataFrame()
arrays_list = []
arraylistFileNames = []
arraylistFileNames2 = []
focusNos = 128*10*60

for file in files5:
    matFile = scipy.io.loadmat(PATH + file)
    matFile['o']['sampFreq'][0][0][0][0]
    array1 = matFile['o']['data'][0, 0][:, 3:17]

    # for array in arrays_list:
    arrays_list.append(array1)
    print(file)
    arraylistFileNames.append(file)
arraylistFileNames2
for array in arrays_list:
    df = pd.DataFrame(array)
    df['id'] = np.arange(df.shape[0])
    df['target'] = np.where(df['id'] < focusNos, 'Focus', 'Unfocus')
    df5 = df5.append(df)
df5 = df5.drop(columns = 'id')
print(df5.shape)

eeg_record31.mat
eeg_record32.mat
eeg_record33.mat
eeg_record34.mat
(1804932, 15)

In [ ]:
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)
print(df5.shape)

(1776340, 15)
(2121504, 15)
(1872140, 15)
(1701412, 15)
(1804932, 15)

### Data Visualisation:

In [ ]:
# # Data Visualisation:
# import numpy as np
# import pandas as pd 
# import mne

# path = PATH
# # data = pd.read_csv(path + 'file.csv', 
# #                    skiprows=0, usecols=[*range(0, 17)]) 
# ch_names = ['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6', 'F4', 'F8', 'AF4']

# sfreq = 128 
# info = mne.create_info(ch_names = ch_names, sfreq = sfreq)
# raw = mne.io.RawArray(df.transpose(), info)
# raw.plot()

In [ ]:
# # Data Visualisation:
# import numpy as np
# import pandas as pd 
# import mne

# path = PATH

# ch_names = ['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6', 'F4', 'F8', 'AF4']

# sfreq = 128 
# info = mne.create_info(ch_names = ch_names, sfreq = sfreq)
# raw = mne.io.RawArray(df.transpose(), info)
# raw.plot()



```
# This is formatted as code
```

# Filtering using scipy

In [ ]:
from scipy.io import loadmat
import numpy as np
import pandas as pd
import csv
import pickle
import os
import seaborn as sns
from scipy.signal import butter, filtfilt
from scipy.stats import zscore
import scipy.io

import networkx as nx
import matplotlib.pyplot as plt
import io
import community as community_louvain
import matplotlib.cm as cm
from collections import defaultdict

In [ ]:
for dirname, _, filenames in os.walk('PATH'):
    print('*** ',dirname)
    for filename in filenames:
        #print(os.path.join(dirname, filename))
        print(filename)

In [ ]:
files = os.listdir(PATH)
len(files)

34

In [ ]:
def bp_filter(data, f_lo, f_hi, sf):
    data_filt = np.zeros_like(data)
    f_ny = sf / 2.  # Nyquist frequency
    b_lo = f_lo / f_ny  # normalized frequency [0..1]
    b_hi = f_hi / f_ny  # normalized frequency [0..1]
    # band-pass filter parameters
    p_lp = {"N":6, "Wn":b_hi, "btype":"lowpass", "analog":False, "output":"ba"}
    p_hp = {"N":6, "Wn":b_lo, "btype":"highpass", "analog":False, "output":"ba"}
    bp_b1, bp_a1 = butter(**p_lp)
    bp_b2, bp_a2 = butter(**p_hp)
    data_filt = filtfilt(bp_b1, bp_a1, data, axis=0)
    data_filt = filtfilt(bp_b2, bp_a2, data_filt, axis=0)
    return data_filt

In [ ]:

# #  Function to read in the EEG data and extract the valid lead data, low and high pass filter and z-transform the data.
# #  Returns a dataframe.
def get_EEG_data(PATH, filename):
    # Extract the data from one of these files.
    hz = 128
    #filename = 'eeg_record30.mat'
    mat = scipy.io.loadmat(PATH + filename)
    data = pd.DataFrame.from_dict(mat["o"]["data"][0,0])

    # Limit the data to the 7 valid EEG leads.
    dat = data.filter(list(range(3, 17)))
    dat.columns = list(range(1, 15))
    dat = dat.filter([1,2, 3, 4,5,6, 7, 8, 9,10,11,12,13,14,17], axis=1)
    labels = ['AF3','F7', 'F3','FC5','T7','P7','O1', 'O2','P8','T8', 'FC6','F4','F8','AF4']  # FP2 should really be AF4
    # useful_channels = ['F7','F3','P7','O1','O2','P8','AF4']

    dat.columns = labels

      # Filter the data, high pass 2 Hz, low pass 40 Hz.
    lo, hi = 2, 40
    # Do the filtering.
    datf = bp_filter(dat.to_numpy(), lo, hi, hz)
    
    # Convert back to a dataframe.
    dat = pd.DataFrame({c: datf[:, i] for i,c in enumerate(labels)})

    # Z-transform each column
    #dat = dat.apply(zscore)
    
    return dat

In [ ]:
# df2 = df.drop(columns=['Filename','target'])

In [ ]:
datf1 = df1.drop(columns=['target'])
datf2 = df2.drop(columns=['target'])
datf3 = df3.drop(columns=['target'])
datf4 = df4.drop(columns=['target'])
datf5 = df5.drop(columns=['target'])

datf1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,4440.512821,3804.102564,5210.769231,3829.230769,4030.25641,4490.769231,3862.051282,3511.794872,4321.025641,4304.615385,4141.025641,4282.564103,4333.846154,4024.102564
1,4440.512821,3796.410256,5205.641026,3827.179487,4030.25641,4489.230769,3858.461538,3505.128205,4311.794872,4304.615385,4144.615385,4282.564103,4335.384615,4017.948718
2,4440.512821,3798.974359,5207.179487,3827.692308,4030.25641,4489.230769,3865.128205,3511.794872,4313.846154,4304.615385,4148.717949,4282.564103,4334.871795,4018.974359
3,4440.512821,3801.538462,5210.256410,3830.769231,4030.25641,4490.256410,3866.153846,3511.282051,4315.897436,4304.615385,4146.666667,4282.564103,4334.358974,4022.051282
4,4440.512821,3799.487179,5210.256410,3831.794872,4030.25641,4490.256410,3865.641026,3506.153846,4311.282051,4304.615385,4145.641026,4282.564103,4333.846154,4020.512821

In [ ]:
datf1.shape

(1776340, 14)

In [ ]:

# Filter the data, high pass 2 Hz, low pass 40 Hz.
lo, hi = 2, 40
hz = 128
# Do the filtering.

datf1 = bp_filter(datf1.to_numpy(), lo, hi, hz)
datf2 = bp_filter(datf2.to_numpy(), lo, hi, hz)
datf3 = bp_filter(datf3.to_numpy(), lo, hi, hz)
datf4 = bp_filter(datf4.to_numpy(), lo, hi, hz)
datf5 = bp_filter(datf5.to_numpy(), lo, hi, hz)

In [ ]:
datf1

array([[ 0.08228662, -1.77988349, -0.90481117, ..., -0.03044844,
         0.05102848,  0.34094785],
       [ 0.06113498, -7.54197381, -5.76272608, ..., -0.03686741,
         1.48971835, -4.708565  ],
       [ 0.03891988, -4.52603511, -4.38960755, ..., -0.04199263,
         1.20785474, -3.43252705],
       ...,
       [ 1.15076555, 23.74912136, 15.07206542, ..., -0.66885569,
        -0.30266626, 19.00258644],
       [ 0.87211985, 12.76575127,  8.80355239, ..., -0.57110744,
        -0.43702851,  7.60147289],
       [ 0.63227624,  4.53175607,  1.96043331, ..., -0.46863573,
         0.1276499 ,  0.31008615]])

In [ ]:
df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,target
0,4440.512821,3804.102564,5210.769231,3829.230769,4030.256410,4490.769231,3862.051282,3511.794872,4321.025641,4304.615385,4141.025641,4282.564103,4333.846154,4024.102564,Focus
1,4440.512821,3796.410256,5205.641026,3827.179487,4030.256410,4489.230769,3858.461538,3505.128205,4311.794872,4304.615385,4144.615385,4282.564103,4335.384615,4017.948718,Focus
2,4440.512821,3798.974359,5207.179487,3827.692308,4030.256410,4489.230769,3865.128205,3511.794872,4313.846154,4304.615385,4148.717949,4282.564103,4334.871795,4018.974359,Focus
3,4440.512821,3801.538462,5210.256410,3830.769231,4030.256410,4490.256410,3866.153846,3511.282051,4315.897436,4304.615385,4146.666667,4282.564103,4334.358974,4022.051282,Focus
4,4440.512821,3799.487179,5210.256410,3831.794872,4030.256410,4490.256410,3865.641026,3506.153846,4311.282051,4304.615385,4145.641026,4282.564103,4333.846154,4020.512821,Focus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398811,4431.282051,4070.256410,5089.743590,3821.538462,4031.282051,4362.564103,4373.846154,4138.974359,4232.307692,4314.871795,4144.615385,4291.794872,4336.410256,4158.974359,Unfocus
398812,4431.794872,4066.153846,5091.282051,3816.923077,4030.769231,4366.153846,4359.487179,4139.487179,4232.820513,4318.974359,4151.794872,4291.794872,4336.410256,4170.256410,Unfocus
398813,4432.307692,4053.846154,5088.717949,3817.948718,4029.230769,4360.512821,4335.384615,4126.666667,4230.769231,4317.948718,4151.282051,4291.794872,4335.897436,4168.717949,Unfocus
398814,4431.282051,4042.051282,5082.564103,3818.461538,4030.256410,4353.333333,4328.205128,4105.641026,4219.487179,4318.461538,4150.769231,4291.794872,4335.897436,4156.410256,Unfocus
398815,4430.769231,4030.769231,5075.897436,3816.923077,4030.256410,4346.153846,4320.000000,4093.333333,4210.256410,4319.487179,4153.846154,4291.794872,4336.410256,4150.256410,Unfocus

In [ ]:
df1['target']

0           Focus
1           Focus
2           Focus
3           Focus
4           Focus
           ...
398811    Unfocus
398812    Unfocus
398813    Unfocus
398814    Unfocus
398815    Unfocus
Name: target, Length: 1776340, dtype: object

In [ ]:
# df1['target']
type(datf1)

numpy.ndarray

In [ ]:
len(datf1)

1776340

In [ ]:
# dfilter1.shape

In [ ]:
dfilter1 = pd.DataFrame(datf1)
dfilter1.shape

(1776340, 14)

In [ ]:
df1.shape

(1776340, 15)

In [ ]:
df1 = df1.reset_index(drop=True)
dfilter1['target'] = df1['target']
dfilter1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,target
0,0.082287,-1.779883,-0.904811,-0.105007,0.162734,-0.216053,-0.204367,-1.188365,-1.756227,0.019028,-0.815825,-0.030448,0.051028,0.340948,Focus
1,0.061135,-7.541974,-5.762726,-2.269905,0.169065,-1.846661,-0.875720,-4.894565,-9.602011,0.017402,3.328369,-0.036867,1.489718,-4.708565,Focus
2,0.038920,-4.526035,-4.389608,-1.318582,0.174081,-1.715748,3.948902,0.053998,-6.782789,0.015517,5.692324,-0.041993,1.207855,-3.432527,Focus
3,0.010396,-0.077865,-0.832547,1.127395,0.177457,-0.779178,8.529421,2.761760,-3.750922,0.013378,4.810988,-0.048003,0.233618,-0.030107,Focus
4,-0.016888,-0.433308,-1.054677,2.566709,0.178986,-0.871482,9.630071,-0.181173,-6.697747,0.010993,3.342445,-0.055054,0.248620,0.443405,Focus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1776335,-0.742876,34.139902,16.205276,0.811966,-0.426722,11.437049,41.442510,48.721797,31.005257,-2.015528,-2.094274,-0.689565,0.121835,11.366084,Unfocus
1776336,0.810413,34.068349,18.198977,-1.501234,-0.352551,16.847476,34.036179,48.890931,29.467668,1.204700,3.733896,-0.720255,0.145244,21.340043,Unfocus
1776337,1.150766,23.749121,15.072065,-1.505534,-1.217224,13.218626,14.429379,37.202298,24.225949,1.201561,3.009671,-0.668856,-0.302666,19.002586,Unfocus
1776338,0.872120,12.765751,8.803552,1.289044,-0.737437,5.262571,5.401500,18.697379,14.674156,-0.653241,-0.105534,-0.571107,-0.437029,7.601473,Unfocus
1776339,0.632276,4.531756,1.960433,0.301131,-0.005190,0.054161,3.213943,6.718739,2.649801,0.506639,2.016326,-0.468636,0.127650,0.310086,Unfocus

In [ ]:
dfilter2 = pd.DataFrame(datf2)
df2 = df2.reset_index(drop=True)
dfilter2['target'] = df2['target']

In [ ]:
dfilter3 = pd.DataFrame(datf3)
df3 = df3 .reset_index(drop=True)
dfilter3['target'] = df3['target']

In [ ]:
dfilter4 = pd.DataFrame(datf4)
df4 = df4.reset_index(drop=True)
dfilter4['target'] = df4['target']

In [ ]:
dfilter5 = pd.DataFrame(datf5)
df5 = df5.reset_index(drop=True)
dfilter5['target'] = df5['target']

In [ ]:
print(len(dfilter1))
print(len(dfilter2))
print(len(dfilter3))
print(len(dfilter4))
print(len(dfilter5))

1776340
2121504
1872140
1701412
1804932

In [ ]:
dfilter1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,target
0,0.082287,-1.779883,-0.904811,-0.105007,0.162734,-0.216053,-0.204367,-1.188365,-1.756227,0.019028,-0.815825,-0.030448,0.051028,0.340948,Focus
1,0.061135,-7.541974,-5.762726,-2.269905,0.169065,-1.846661,-0.875720,-4.894565,-9.602011,0.017402,3.328369,-0.036867,1.489718,-4.708565,Focus
2,0.038920,-4.526035,-4.389608,-1.318582,0.174081,-1.715748,3.948902,0.053998,-6.782789,0.015517,5.692324,-0.041993,1.207855,-3.432527,Focus
3,0.010396,-0.077865,-0.832547,1.127395,0.177457,-0.779178,8.529421,2.761760,-3.750922,0.013378,4.810988,-0.048003,0.233618,-0.030107,Focus
4,-0.016888,-0.433308,-1.054677,2.566709,0.178986,-0.871482,9.630071,-0.181173,-6.697747,0.010993,3.342445,-0.055054,0.248620,0.443405,Focus

In [ ]:
dfilter2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,target
0,0.082287,-1.779883,-0.904811,-0.105007,0.162734,-0.216053,-0.204367,-1.188365,-1.756227,0.019028,-0.815825,-0.030448,0.051028,0.340948,Focus
1,0.061135,-7.541974,-5.762726,-2.269905,0.169065,-1.846661,-0.875720,-4.894565,-9.602011,0.017402,3.328369,-0.036867,1.489718,-4.708565,Focus
2,0.038920,-4.526035,-4.389608,-1.318582,0.174081,-1.715748,3.948902,0.053998,-6.782789,0.015517,5.692324,-0.041993,1.207855,-3.432527,Focus
3,0.010396,-0.077865,-0.832547,1.127395,0.177457,-0.779178,8.529421,2.761760,-3.750922,0.013378,4.810988,-0.048003,0.233618,-0.030107,Focus
4,-0.016888,-0.433308,-1.054677,2.566709,0.178986,-0.871482,9.630071,-0.181173,-6.697747,0.010993,3.342445,-0.055054,0.248620,0.443405,Focus

In [ ]:
# dfilter1.set_index('target').to_dict()

In [ ]:
columns = ['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6', 'F4', 'F8', 'AF4','target'] # (15 channels)
useless_channels = ['AF3', 'FC5', 'T7','T8', 'FC6', 'F4', 'F8']
useful_channels = ['F7','F3','P7','O1','O2','P8','AF4']
dfilter1.columns = columns # (15 channels)
dfilter1 = dfilter1.drop(columns = useless_channels)
dfilter2.columns  = columns
dfilter2 = dfilter2.drop(columns = useless_channels)
dfilter3.columns = columns
dfilter3 = dfilter3.drop(columns = useless_channels)
dfilter4.columns = columns
dfilter4 = dfilter4.drop(columns = useless_channels)
dfilter5.columns = columns
dfilter5 = dfilter5.drop(columns = useless_channels)

In [ ]:
dfilter2

,F7,F3,P7,O1,O2,P8,AF4,target
0,-1.779883,-0.904811,-0.216053,-0.204367,-1.188365,-1.756227,0.340948,Focus
1,-7.541974,-5.762726,-1.846661,-0.875720,-4.894565,-9.602011,-4.708565,Focus
2,-4.526035,-4.389608,-1.715748,3.948902,0.053998,-6.782789,-3.432527,Focus
3,-0.077865,-0.832547,-0.779178,8.529421,2.761760,-3.750922,-0.030107,Focus
4,-0.433308,-1.054677,-0.871482,9.630071,-0.181173,-6.697747,0.443405,Focus
...,...,...,...,...,...,...,...,...
2121499,-2.243973,-8.576292,0.008118,-0.514750,0.039802,-2.358954,-4.447746,Unfocus
2121500,4.713443,-7.331808,-0.010633,1.013342,2.629341,-1.235873,-1.551437,Unfocus
2121501,2.770823,-11.384716,-4.528272,-0.939100,-1.260089,-3.511733,-9.048450,Unfocus
2121502,-2.261944,-12.227357,-5.847283,-3.122579,-5.639936,-4.672692,-12.361727,Unfocus
2121503,-2.415049,-3.137463,-1.427137,-1.983763,-1.013000,-1.145483,-1.699232,Unfocus

In [ ]:
# Z-transform each column
# dfilter = dfilter.apply(zscore)

In [ ]:
dfilter1.head()

         F7        F3        P7        O1        O2        P8       AF4 target
0 -1.779883 -0.904811 -0.216053 -0.204367 -1.188365 -1.756227  0.340948  Focus
1 -7.541974 -5.762726 -1.846661 -0.875720 -4.894565 -9.602011 -4.708565  Focus
2 -4.526035 -4.389608 -1.715748  3.948902  0.053998 -6.782789 -3.432527  Focus
3 -0.077865 -0.832547 -0.779178  8.529421  2.761760 -3.750922 -0.030107  Focus
4 -0.433308 -1.054677 -0.871482  9.630071 -0.181173 -6.697747  0.443405  Focus

In [ ]:
dfilter1.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter1.csv')
dfilter2.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter2.csv')
dfilter3.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter3.csv')
dfilter4.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter4.csv')
dfilter5.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter5.csv')

In [ ]:
# #Focused wave plot
# labels = ['F7', 'F3', 'P7', 'O1', 'O2', 'P8', 'AF4']
# start = 5*60*128
# seconds = 5
# hz = 128
# state="focused"
# plotleads(dfilter, labels, start, seconds, hz,state)

In [ ]:
# #UnFocused  wave plot
# labels = ['F7', 'F3', 'P7', 'O1', 'O2', 'P8', 'AF4']
# start =20* 60*128
# seconds = 5
# hz = 128
# state="unfocused"
# plotleads(dat, labels, start, seconds, hz,state)

In [ ]:
# dfilter.to_csv('/content/drive/MyDrive/CSVsb4filterADHDAndNon/DS-II_filtered.csv')

### To ICA

In [ ]:
# dfilter = pd.read_csv('/content/drive/MyDrive/CSVsb4filterADHDAndNon/DS-II_filtered.csv')
# dftoICA = dfilter.drop(columns=['Filename','target'])

In [ ]:
# dftoICA = dftoICA.drop(columns=['Unnamed: 0'])

In [ ]:
# dftoICA.head()

In [ ]:
# dftoICA.value_counts()

In [ ]:
dfilter1 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter1.csv', index_col = 0)
dfilter2 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter2.csv', index_col = 0)
dfilter3 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter3.csv', index_col = 0)
dfilter4 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter4.csv', index_col = 0)
dfilter5 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter5.csv', index_col = 0)

##Apply ICA to filtered data

In [ ]:
from sklearn.datasets import load_digits
from sklearn.decomposition import FastICA
def filter(X):
  transformer = FastICA(n_components=7,random_state=0,whiten='unit-variance')
  X_trans = transformer.fit_transform(X) #Had worked with df at beginning.
  X_trans.shape
  return X_trans

# (1797, 7)
# print(X_trans[0:5, :])
# print(X_trans.shape)

In [ ]:

dfICA1 = pd.DataFrame(filter(dfilter1.drop(columns = 'target')))

In [ ]:
dfICA2 = pd.DataFrame(filter(dfilter2.drop(columns = 'target')))
dfICA3 = pd.DataFrame(filter(dfilter3.drop(columns = 'target')))
dfICA4 = pd.DataFrame(filter(dfilter4.drop(columns = 'target')))
dfICA5 = pd.DataFrame(filter(dfilter5.drop(columns = 'target')))

In [ ]:
dfICA1['target'] = df1['target']
dfICA2['target'] = df2['target']
dfICA3['target'] = df3['target']
dfICA4['target'] = df4['target']
dfICA5['target'] = df5['target']

In [ ]:
dfICA1

,0,1,2,3,4,5,6,target
0,0.000143,2.388629e-05,-0.000059,0.000127,0.000103,0.000083,-3.968756e-07,Focus
1,0.000227,2.324648e-04,-0.000508,0.000452,0.000589,0.000303,3.119872e-04,Focus
2,0.000212,1.234892e-04,-0.000207,0.000569,0.000457,0.000355,6.329678e-04,Focus
3,0.000326,1.504605e-04,0.000148,0.000483,0.000126,0.000601,6.850016e-04,Focus
4,0.000556,3.037743e-04,0.000092,0.000436,0.000134,0.000981,6.735739e-04,Focus
...,...,...,...,...,...,...,...,...
1776335,-0.000525,-1.184961e-03,0.001512,0.000555,-0.001776,-0.000253,2.541339e-03,Unfocus
1776336,0.000470,-1.232506e-03,0.000997,0.000413,-0.002081,-0.001096,1.842349e-03,Unfocus
1776337,0.000414,-9.429528e-04,0.000672,0.000125,-0.001653,-0.002012,6.913090e-04,Unfocus
1776338,-0.000177,-4.155183e-04,0.000554,-0.000110,-0.000890,-0.001169,2.214483e-04,Unfocus
1776339,-0.000070,-4.119381e-07,0.000266,-0.000048,-0.000208,-0.000294,3.608483e-04,Unfocus

In [ ]:
dfICA2

,0,1,2,3,4,5,6,target
0,0.000076,-0.000040,-9.459730e-06,0.000122,-0.000117,0.000088,0.000101,Focus
1,-0.000212,-0.000264,6.434022e-07,0.000449,-0.000559,0.000303,0.000482,Focus
2,-0.000171,-0.000380,3.882881e-04,0.000553,-0.000488,0.000190,0.000334,Focus
3,0.000038,-0.000291,7.021588e-04,0.000465,-0.000454,0.000324,0.000045,Focus
4,0.000139,-0.000287,7.749343e-04,0.000433,-0.000686,0.000693,0.000050,Focus
...,...,...,...,...,...,...,...,...
2121499,-0.000297,-0.000915,-2.011459e-04,0.000030,0.000055,-0.000107,0.000286,Unfocus
2121500,-0.000009,-0.001016,-4.831855e-05,-0.000558,-0.000023,-0.000241,-0.000070,Unfocus
2121501,-0.000496,-0.001052,2.026627e-04,-0.000783,0.000189,-0.000143,0.000173,Unfocus
2121502,-0.000759,-0.000834,1.491336e-04,-0.000535,0.000328,0.000094,0.000442,Unfocus
2121503,-0.000055,-0.000177,-4.546679e-05,0.000041,0.000071,-0.000106,0.000202,Unfocus

In [ ]:
useful_channels = ['F7','F3','P7','O1','O2','P8','AF4','target'] #(8 elements )
dfICA1.columns = useful_channels # (15 channels)
dfICA2.columns = useful_channels # (15 channels)
dfICA3.columns = useful_channels # (15 channels)
dfICA4.columns = useful_channels # (15 channels)
dfICA5.columns = useful_channels # (15 channels)

In [ ]:
dfICA2

,F7,F3,P7,O1,O2,P8,AF4,target
0,0.000076,-0.000040,-9.459730e-06,0.000122,-0.000117,0.000088,0.000101,Focus
1,-0.000212,-0.000264,6.434022e-07,0.000449,-0.000559,0.000303,0.000482,Focus
2,-0.000171,-0.000380,3.882881e-04,0.000553,-0.000488,0.000190,0.000334,Focus
3,0.000038,-0.000291,7.021588e-04,0.000465,-0.000454,0.000324,0.000045,Focus
4,0.000139,-0.000287,7.749343e-04,0.000433,-0.000686,0.000693,0.000050,Focus
...,...,...,...,...,...,...,...,...
2121499,-0.000297,-0.000915,-2.011459e-04,0.000030,0.000055,-0.000107,0.000286,Unfocus
2121500,-0.000009,-0.001016,-4.831855e-05,-0.000558,-0.000023,-0.000241,-0.000070,Unfocus
2121501,-0.000496,-0.001052,2.026627e-04,-0.000783,0.000189,-0.000143,0.000173,Unfocus
2121502,-0.000759,-0.000834,1.491336e-04,-0.000535,0.000328,0.000094,0.000442,Unfocus
2121503,-0.000055,-0.000177,-4.546679e-05,0.000041,0.000071,-0.000106,0.000202,Unfocus

In [ ]:
dfICA1.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfICA1.csv')
dfICA2.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfICA2.csv')
dfICA3.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfICA3.csv')
dfICA4.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfICA4.csv')
dfICA5.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfICA5.csv')

In [ ]:
# dfICA.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfICAFilteredNew.csv')

### Bands

In [ ]:
# df4 = pd.read_csv('/content/drive/MyDrive/CSVsb4filterADHDAndNon/DS-II_filtered.csv')

In [ ]:
# df4 = df4.drop(columns=['Filename'])
# df4

In [ ]:
# df4 = df4.drop(columns=['Unnamed: 0'])
# df4

In [ ]:
# dfilter = pd.read_csv('/content/drive/MyDrive/CSVsb4filterADHDAndNon/DS-II_filtered.csv')
# dfToPowers = df4.drop(columns=['target'])

In [ ]:
# dfToPowers = dftoICA.copy()
# useful_channels = ['F7','F3','P7','O1','O2','P8','AF4','target'] #(8 elements )

In [ ]:
import numpy as np
import pandas as pd
import os
import scipy.io
import matplotlib.pyplot as plt
from scipy import signal

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# dToBands1 = dfICA1
# dToBands2 = dfICA2
# dToBands3 = dfICA3
# dToBands4 = dfICA4
# dToBands5 = dfICA5

In [ ]:
dToBands1 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter1.csv', index_col = 0)
dToBands2 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter2.csv', index_col = 0)
dToBands3 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter3.csv', index_col = 0)
dToBands4 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter4.csv', index_col = 0)
dToBands5 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter5.csv', index_col = 0)

In [ ]:
dToBands1

,F7,F3,P7,O1,O2,P8,AF4,target
0,-1.779883,-0.904811,-0.216053,-0.204367,-1.188365,-1.756227,0.340948,Focus
1,-7.541974,-5.762726,-1.846661,-0.875720,-4.894565,-9.602011,-4.708565,Focus
2,-4.526035,-4.389608,-1.715748,3.948902,0.053998,-6.782789,-3.432527,Focus
3,-0.077865,-0.832547,-0.779178,8.529421,2.761760,-3.750922,-0.030107,Focus
4,-0.433308,-1.054677,-0.871482,9.630071,-0.181173,-6.697747,0.443405,Focus
...,...,...,...,...,...,...,...,...
1776335,34.139902,16.205276,11.437049,41.442510,48.721797,31.005257,11.366084,Unfocus
1776336,34.068349,18.198977,16.847476,34.036179,48.890931,29.467668,21.340043,Unfocus
1776337,23.749121,15.072065,13.218626,14.429379,37.202298,24.225949,19.002586,Unfocus
1776338,12.765751,8.803552,5.262571,5.401500,18.697379,14.674156,7.601473,Unfocus
1776339,4.531756,1.960433,0.054161,3.213943,6.718739,2.649801,0.310086,Unfocus

In [ ]:
# dToBands10 = dToBands1.head(10)
dToBands1Focus = dToBands1[dToBands1['target'] == 'Focus']
dToBands1UnFocus = dToBands1[dToBands1['target'] == 'Unfocus']
dToBands2Focus = dToBands2[dToBands2['target'] == 'Focus']
dToBands2UnFocus = dToBands2[dToBands2['target'] == 'Unfocus']
dToBands3Focus = dToBands3[dToBands3['target'] == 'Focus']
dToBands3UnFocus = dToBands3[dToBands3['target'] == 'Unfocus']
dToBands4Focus = dToBands4[dToBands4['target'] == 'Focus']
dToBands4UnFocus = dToBands4[dToBands4['target'] == 'Unfocus']
dToBands5Focus = dToBands5[dToBands5['target'] == 'Focus']
dToBands5UnFocus = dToBands5[dToBands5['target'] == 'Unfocus']

In [ ]:
dfFocusArray1 = np.array(dToBands1Focus)
dfFocusArray2 = np.array(dToBands2Focus)
dfFocusArray3 = np.array(dToBands3Focus)
dfFocusArray4 = np.array(dToBands4Focus)
dfFocusArray5 = np.array(dToBands5Focus)

dfFocusArray1

array([[-1.7798834874564609, -0.9048111668020188, -0.2160534263471631,
        ..., -1.7562274679936576, 0.3409478472501497, 'Focus'],
       [-7.541973805269903, -5.7627260781024825, -1.8466614601114109,
        ..., -9.602010711978258, -4.708565001538795, 'Focus'],
       [-4.526035111603302, -4.389607547613142, -1.7157482374770094, ...,
        -6.782788727649638, -3.4325270482999093, 'Focus'],
       ...,
       [-0.1825162486172176, 0.1743015820615112, -0.5388606796462261,
        ..., 5.81404344529654, 2.9999701041607083, 'Focus'],
       [-4.06555805914029, -5.85555067456678, -3.1008901955816315, ...,
        -3.071744832158715, -0.7735901074065716, 'Focus'],
       [-4.676676815001407, -6.154350018539237, -4.515364264620324, ...,
        -7.14075108647973, -0.1379737675820931, 'Focus']], dtype=object)

In [ ]:
dfUnfocusArray1 = np.array(dToBands1UnFocus)
dfUnfocusArray2 = np.array(dToBands2UnFocus)
dfUnfocusArray3 = np.array(dToBands3UnFocus)
dfUnfocusArray4 = np.array(dToBands4UnFocus)
dfUnfocusArray5 = np.array(dToBands5UnFocus)
dfUnfocusArray1

array([[-24.233184554840697, -16.887088929844396, -6.138996956190967,
        ..., -10.076484389350428, -20.557651224912977, 'Unfocus'],
       [-31.850406134645617, -21.49526348626922, -18.846587593621106,
        ..., -17.647969241412767, -21.96724717038821, 'Unfocus'],
       [-38.26153811725559, -22.417761962206463, -24.02651063373568, ...,
        -20.67971685746847, -23.308531543844204, 'Unfocus'],
       ...,
       [23.749121364367323, 15.07206542467615, 13.21862645002699, ...,
        24.225949319563963, 19.00258644027777, 'Unfocus'],
       [12.765751272302964, 8.803552390387015, 5.262570755787224, ...,
        14.674156382497063, 7.601472894492348, 'Unfocus'],
       [4.531756067728473, 1.9604333051446936, 0.0541608103325135, ...,
        2.6498010806942105, 0.3100861472257019, 'Unfocus']], dtype=object)

In [ ]:
# sf=128
# i_ch = 0
# time = np.arange(128) / sf
# channel = datadf2[:128, channel_range[i_ch]]
# plt.plot(time, channel)
# plt.xlabel('time (s)')
# plt.ylabel(f'EEG channel {channel_list[i_ch]}')

In [ ]:
states1 = {
 'Focus': dfFocusArray1[:, :],
}
states2 = {
 'Focus': dfFocusArray2[:, :],
}
states3 = {
 'Focus': dfFocusArray3[:, :],
}
states4 = {
 'Focus': dfFocusArray4[:, :],
}
states5 = {
 'Focus': dfFocusArray5[:, :],
}
states1.items()

dict_items([('Focus', array([[-1.7798834874564609, -0.9048111668020188, -0.2160534263471631,
        ..., -1.7562274679936576, 0.3409478472501497, 'Focus'],
       [-7.541973805269903, -5.7627260781024825, -1.8466614601114109,
        ..., -9.602010711978258, -4.708565001538795, 'Focus'],
       [-4.526035111603302, -4.389607547613142, -1.7157482374770094, ...,
        -6.782788727649638, -3.4325270482999093, 'Focus'],
       ...,
       [-0.1825162486172176, 0.1743015820615112, -0.5388606796462261,
        ..., 5.81404344529654, 2.9999701041607083, 'Focus'],
       [-4.06555805914029, -5.85555067456678, -3.1008901955816315, ...,
        -3.071744832158715, -0.7735901074065716, 'Focus'],
       [-4.676676815001407, -6.154350018539237, -4.515364264620324, ...,
        -7.14075108647973, -0.1379737675820931, 'Focus']], dtype=object))])

In [ ]:
states5

{'Focus': array([[-0.06438144554303, 0.2634013012956817, -0.4606968233945574, ...,
         -0.0020978517279388, 0.0236251209633948, 'Focus'],
        [-0.1792133477777016, 2.000869517974985, 4.0993779601481, ...,
         -6.51267515025145, -5.948952712813652, 'Focus'],
        [-0.8550509685936882, 1.8357485576124728, 3.7892055115915104, ...,
         -6.391623061044247, -5.7252253560629, 'Focus'],
        ...,
        [-1.3122312050302534, -1.6954336090002933, 6.629356971955323, ...,
         0.8588860829329832, 7.259009479939149, 'Focus'],
        [0.0904926411465183, -3.0991921365479804, 2.1292972534315604, ...,
         -0.5531983717775226, 7.848827285010253, 'Focus'],
        [6.956419333932342, -0.3391755221965127, 5.465697302025696, ...,
         -2.708473602571811, 8.610538429010203, 'Focus']], dtype=object)}

In [ ]:
states6 = {
  'Unfocus': dfUnfocusArray1[:, :],
  # 'Unfocus': dfUnfocusArray2[:, :],
  # 'Unfocus': dfUnfocusArray3[:, :],
  # 'Unfocus': dfUnfocusArray4[:, :],
  # 'Unfocus': dfUnfocusArray5[:, :],
}
states7 = {
  'Unfocus': dfUnfocusArray2[:, :],
}
states8 = {

  'Unfocus': dfUnfocusArray3[:, :],
}
states9 = {
  'Unfocus': dfUnfocusArray4[:, :],
}
states10 = {
  'Unfocus': dfUnfocusArray5[:, :],
}
states6.items()

dict_items([('Unfocus', array([[-0.5959730513014558, -8.211370831016087, -7.933999340014477, ...,
        -8.143597932492767, -3.887129987113356, 'Unfocus'],
       [2.765916771045162, -6.194996298012546, -3.1466208435537117, ...,
        -10.98144479014383, -6.67110079613191, 'Unfocus'],
       [5.317437487738809, -5.000760056694503, -4.520134030058514, ...,
        -10.366171354224184, -3.862697060876326, 'Unfocus'],
       ...,
       [5.377156500806365, -1.6013280085896475, 1.0977676255858584, ...,
        2.020545283762376, 4.464533622135592, 'Unfocus'],
       [4.765789727809849, 1.840551949934274, -1.1239462024519875, ...,
        -0.8351387559885151, -0.1280349007093262, 'Unfocus'],
       [3.178396406586796, 3.302219227603315, 3.297388403975136, ...,
        4.978754644762813, 3.377000913686792, 'Unfocus']], dtype=object))])

In [ ]:
bands = {'alpha': (8, 13), 'delta': (0.5, 4), 'beta': (13, 30), 'gamma': (30, np.inf)}

In [ ]:
def get_powers(channel, sf=128):
    channel = channel - channel.mean()
    freq, psd = signal.periodogram(channel, fs=sf, nfft=256)

    powers = {}
    for band_name, band_limits in bands.items():
        low, high = band_limits
        powers[band_name] = psd[(freq >= low) & (freq < high)].mean().real
    return powers

In [ ]:

# df1  

def listOfRows(states):
  listOfRows = []
# for subject_idx in subjects:
    #states = get_data(f"eeg_record{subject_idx}.mat")
  for ch_name, ch_idx in channel_mymap.items():
        for state, eeg in states.items():
            powers = get_powers(eeg[:, ch_idx])
            powers['state'] = state
            powers['channel'] = ch_name
            # powers['subject'] = f"subject_{subject_idx}"
            listOfRows.append(powers)   
  return listOfRows

In [ ]:

# # df1
# listOfRows1 = []
# # for subject_idx in subjects:
#     #states = get_data(f"eeg_record{subject_idx}.mat")
# for ch_name, ch_idx in channel_mymap.items():
#         for state, eeg in states1.items():
#             powers = get_powers(eeg[:, ch_idx])
#             powers['state'] = state
#             powers['channel'] = ch_name
#             # powers['subject'] = f"subject_{subject_idx}"
#             listOfRows1.append(powers)

In [ ]:
states1

{'Focus': array([[-1.7798834874564609, -0.9048111668020188, -0.2160534263471631,
         ..., -1.7562274679936576, 0.3409478472501497, 'Focus'],
        [-7.541973805269903, -5.7627260781024825, -1.8466614601114109,
         ..., -9.602010711978258, -4.708565001538795, 'Focus'],
        [-4.526035111603302, -4.389607547613142, -1.7157482374770094, ...,
         -6.782788727649638, -3.4325270482999093, 'Focus'],
        ...,
        [-0.1825162486172176, 0.1743015820615112, -0.5388606796462261,
         ..., 5.81404344529654, 2.9999701041607083, 'Focus'],
        [-4.06555805914029, -5.85555067456678, -3.1008901955816315, ...,
         -3.071744832158715, -0.7735901074065716, 'Focus'],
        [-4.676676815001407, -6.154350018539237, -4.515364264620324, ...,
         -7.14075108647973, -0.1379737675820931, 'Focus']], dtype=object)}

In [ ]:
type(states2)

dict

In [ ]:
channel_range = np.array(range(0, 7))
channel_list = ['F7','F3','P7','O1','O2','P8','AF4'] #(7chs)
channel_mymap = dict(zip(channel_list, channel_range))

In [ ]:
# listOfRows = []
listOfRowsFocus1 = listOfRows(states1)
listOfRowsFocus2 = listOfRows(states2)
listOfRowsFocus3 = listOfRows(states3)
listOfRowsFocus4 = listOfRows(states4)
listOfRowsFocus5 = listOfRows(states5)
listOfRowsUnfocus1 = listOfRows(states6)
listOfRowsUnfocus2 = listOfRows(states7)
listOfRowsUnfocus3 = listOfRows(states8)
listOfRowsUnfocus4 = listOfRows(states9)
listOfRowsUnfocus5 = listOfRows(states10)
# listOfRows = listOfRows1.append(listOfRows2)
type(listOfRowsFocus1)

list

In [ ]:
listOfRowsFocus1

[{'alpha': 21.582477632516333,
  'delta': 75.81440636059905,
  'beta': 9.23599100591356,
  'gamma': 0.7087991642172614,
  'state': 'Focus',
  'channel': 'F7'},
 {'alpha': 1.1735159863863298,
  'delta': 5.487767263909073,
  'beta': 1.0752366499391133,
  'gamma': 0.14206821401427122,
  'state': 'Focus',
  'channel': 'F3'},
 {'alpha': 1.7958852292383272,
  'delta': 31.36723933761163,
  'beta': 0.8374566470989908,
  'gamma': 0.11788684313519741,
  'state': 'Focus',
  'channel': 'P7'},
 {'alpha': 18.083213311154395,
  'delta': 52.50545828091001,
  'beta': 7.819184547161569,
  'gamma': 0.7774531000664558,
  'state': 'Focus',
  'channel': 'O1'},
 {'alpha': 44.82245100038131,
  'delta': 191.98019364869015,
  'beta': 17.11647930848591,
  'gamma': 1.2707343358682908,
  'state': 'Focus',
  'channel': 'O2'},
 {'alpha': 1.4694706164137064,
  'delta': 8.405305099506188,
  'beta': 1.8151626710053963,
  'gamma': 0.19064289450520444,
  'state': 'Focus',
  'channel': 'P8'},
 {'alpha': 3.766178720503102,
  'delta': 15.596748352827253,
  'beta': 2.0911289626068714,
  'gamma': 0.26626304287519803,
  'state': 'Focus',
  'channel': 'AF4'}]

In [ ]:
listOfRows2 = listOfRows(states2)
listOfRows2

[{'alpha': 21.582477632416953,
  'delta': 75.81440636263086,
  'beta': 9.235991005897429,
  'gamma': 0.7087991642167385,
  'state': 'Focus',
  'channel': 'F7'},
 {'alpha': 1.1735159863908455,
  'delta': 5.487767264543087,
  'beta': 1.0752366499410608,
  'gamma': 0.14206821401437297,
  'state': 'Focus',
  'channel': 'F3'},
 {'alpha': 1.7958852291690954,
  'delta': 31.367239333262024,
  'beta': 0.8374566471063261,
  'gamma': 0.11788684313530619,
  'state': 'Focus',
  'channel': 'P7'},
 {'alpha': 18.08321331124017,
  'delta': 52.505458288963915,
  'beta': 7.819184547175198,
  'gamma': 0.7774531000723259,
  'state': 'Focus',
  'channel': 'O1'},
 {'alpha': 44.822451000427066,
  'delta': 191.98019363831546,
  'beta': 17.116479308483935,
  'gamma': 1.2707343358688705,
  'state': 'Focus',
  'channel': 'O2'},
 {'alpha': 1.4694706164643596,
  'delta': 8.405305098493024,
  'beta': 1.8151626710121533,
  'gamma': 0.19064289451050434,
  'state': 'Focus',
  'channel': 'P8'},
 {'alpha': 3.766178720528966,
  'delta': 15.5967483531228,
  'beta': 2.0911289626237095,
  'gamma': 0.26626304287895103,
  'state': 'Focus',
  'channel': 'AF4'}]

In [ ]:
dfrowslistFocus1 = pd.DataFrame.from_dict(listOfRowsFocus1)
dfrowslistFocus2 = pd.DataFrame.from_dict(listOfRowsFocus2)
dfrowslistFocus3 = pd.DataFrame.from_dict(listOfRowsFocus3)
dfrowslistFocus4 = pd.DataFrame.from_dict(listOfRowsFocus4)
dfrowslistFocus5 = pd.DataFrame.from_dict(listOfRowsFocus5)
dfrowslistFocus1

       alpha       delta       beta     gamma  state channel
0  21.582478   75.814406   9.235991  0.708799  Focus      F7
1   1.173516    5.487767   1.075237  0.142068  Focus      F3
2   1.795885   31.367239   0.837457  0.117887  Focus      P7
3  18.083213   52.505458   7.819185  0.777453  Focus      O1
4  44.822451  191.980194  17.116479  1.270734  Focus      O2
5   1.469471    8.405305   1.815163  0.190643  Focus      P8
6   3.766179   15.596748   2.091129  0.266263  Focus     AF4

In [ ]:
dfrowslistUnfocus1 = pd.DataFrame.from_dict(listOfRowsUnfocus1)
dfrowslistUnfocus2 = pd.DataFrame.from_dict(listOfRowsUnfocus2)
dfrowslistUnfocus3 = pd.DataFrame.from_dict(listOfRowsUnfocus3)
dfrowslistUnfocus4 = pd.DataFrame.from_dict(listOfRowsUnfocus4)
dfrowslistUnfocus5 = pd.DataFrame.from_dict(listOfRowsUnfocus5)
dfrowslistUnfocus5

      alpha      delta      beta     gamma    state channel
0  4.758651  23.865132  0.603753  0.096275  Unfocus      F7
1  1.546638   1.009209  0.324108  0.033231  Unfocus      F3
2  3.106714   4.062598  0.597593  0.061847  Unfocus      P7
3  4.157316   7.888724  0.622376  0.075872  Unfocus      O1
4  3.640760   2.592613  0.456683  0.062091  Unfocus      O2
5  3.962184   2.158681  0.569189  0.094259  Unfocus      P8
6  1.173528   1.251538  0.352267  0.048891  Unfocus     AF4

In [ ]:
vertical_concat = pd.concat([dfrowslistFocus1,dfrowslistFocus2, dfrowslistFocus3, dfrowslistUnfocus1,dfrowslistUnfocus2, dfrowslistUnfocus3], axis=0, ignore_index=True)

In [ ]:
vertical_concat

        alpha       delta       beta     gamma    state channel
0   21.582478   75.814406   9.235991  0.708799    Focus      F7
1    1.173516    5.487767   1.075237  0.142068    Focus      F3
2    1.795885   31.367239   0.837457  0.117887    Focus      P7
3   18.083213   52.505458   7.819185  0.777453    Focus      O1
4   44.822451  191.980194  17.116479  1.270734    Focus      O2
5    1.469471    8.405305   1.815163  0.190643    Focus      P8
6    3.766179   15.596748   2.091129  0.266263    Focus     AF4
7   21.582478   75.814406   9.235991  0.708799    Focus      F7
8    1.173516    5.487767   1.075237  0.142068    Focus      F3
9    1.795885   31.367239   0.837457  0.117887    Focus      P7
10  18.083213   52.505458   7.819185  0.777453    Focus      O1
11  44.822451  191.980194  17.116479  1.270734    Focus      O2
12   1.469471    8.405305   1.815163  0.190643    Focus      P8
13   3.766179   15.596748   2.091129  0.266263    Focus     AF4
14   1.313192    1.292633   0.482070  0.068316    Focus      F7
15   1.940559    3.203893   0.654321  0.087033    Focus      F3
16   3.374943    8.030812   0.768921  0.082389    Focus      P7
17   2.366213    9.560376   0.635911  0.122696    Focus      O1
18   2.684648   16.140514   0.767892  0.104459    Focus      O2
19   2.274508    5.442220   0.643466  0.119283    Focus      P8
20   2.736497    2.579588   0.553741  0.064100    Focus     AF4
21   4.758651   23.865132   0.603753  0.096275  Unfocus      F7
22   1.546638    1.009209   0.324108  0.033231  Unfocus      F3
23   3.106714    4.062598   0.597593  0.061847  Unfocus      P7
24   4.157316    7.888724   0.622376  0.075872  Unfocus      O1
25   3.640760    2.592613   0.456683  0.062091  Unfocus      O2
26   3.962184    2.158681   0.569189  0.094259  Unfocus      P8
27   1.173528    1.251538   0.352267  0.048891  Unfocus     AF4
28   1.569356   37.062861   0.549699  0.107984  Unfocus      F7
29   2.085261   19.195052   0.519313  0.117127  Unfocus      F3
30   0.882999   21.597552   0.404765  0.095855  Unfocus      P7
31   2.086651   59.156010   0.643488  0.132323  Unfocus      O1
32   2.121281   43.761955   0.630762  0.102340  Unfocus      O2
33   2.002300   19.057509   0.688112  0.122486  Unfocus      P8
34   1.527285   12.060401   0.627175  0.093167  Unfocus     AF4
35   2.018304    3.548523   0.496081  0.088527  Unfocus      F7
36   2.900375    5.391830   0.454510  0.092746  Unfocus      F3
37   2.140496    8.453167   0.628486  0.059200  Unfocus      P7
38   2.329915    9.603010   0.766771  0.089855  Unfocus      O1
39   2.345177   16.863827   0.839385  0.094189  Unfocus      O2
40   3.134618    6.598900   0.546060  0.106409  Unfocus      P8
41   2.525461    2.779900   0.382307  0.084817  Unfocus     AF4

In [ ]:
vertical_concat.drop(columns = 'channel', inplace = True) # equivanent to vertical_concat = assignment

In [ ]:
vertical_concat

        alpha       delta       beta     gamma    state
0   21.582478   75.814406   9.235991  0.708799    Focus
1    1.173516    5.487767   1.075237  0.142068    Focus
2    1.795885   31.367239   0.837457  0.117887    Focus
3   18.083213   52.505458   7.819185  0.777453    Focus
4   44.822451  191.980194  17.116479  1.270734    Focus
5    1.469471    8.405305   1.815163  0.190643    Focus
6    3.766179   15.596748   2.091129  0.266263    Focus
7   21.582478   75.814406   9.235991  0.708799    Focus
8    1.173516    5.487767   1.075237  0.142068    Focus
9    1.795885   31.367239   0.837457  0.117887    Focus
10  18.083213   52.505458   7.819185  0.777453    Focus
11  44.822451  191.980194  17.116479  1.270734    Focus
12   1.469471    8.405305   1.815163  0.190643    Focus
13   3.766179   15.596748   2.091129  0.266263    Focus
14   1.313192    1.292633   0.482070  0.068316    Focus
15   1.940559    3.203893   0.654321  0.087033    Focus
16   3.374943    8.030812   0.768921  0.082389    Focus
17   2.366213    9.560376   0.635911  0.122696    Focus
18   2.684648   16.140514   0.767892  0.104459    Focus
19   2.274508    5.442220   0.643466  0.119283    Focus
20   2.736497    2.579588   0.553741  0.064100    Focus
21   4.758651   23.865132   0.603753  0.096275  Unfocus
22   1.546638    1.009209   0.324108  0.033231  Unfocus
23   3.106714    4.062598   0.597593  0.061847  Unfocus
24   4.157316    7.888724   0.622376  0.075872  Unfocus
25   3.640760    2.592613   0.456683  0.062091  Unfocus
26   3.962184    2.158681   0.569189  0.094259  Unfocus
27   1.173528    1.251538   0.352267  0.048891  Unfocus
28   1.569356   37.062861   0.549699  0.107984  Unfocus
29   2.085261   19.195052   0.519313  0.117127  Unfocus
30   0.882999   21.597552   0.404765  0.095855  Unfocus
31   2.086651   59.156010   0.643488  0.132323  Unfocus
32   2.121281   43.761955   0.630762  0.102340  Unfocus
33   2.002300   19.057509   0.688112  0.122486  Unfocus
34   1.527285   12.060401   0.627175  0.093167  Unfocus
35   2.018304    3.548523   0.496081  0.088527  Unfocus
36   2.900375    5.391830   0.454510  0.092746  Unfocus
37   2.140496    8.453167   0.628486  0.059200  Unfocus
38   2.329915    9.603010   0.766771  0.089855  Unfocus
39   2.345177   16.863827   0.839385  0.094189  Unfocus
40   3.134618    6.598900   0.546060  0.106409  Unfocus
41   2.525461    2.779900   0.382307  0.084817  Unfocus

In [ ]:
vertical_concat = vertical_concat.rename(columns = {'alpha':'Alpha', 'delta':'Delta', 'beta':'Beta','gamma':'Gamma','state':'Label'})

In [ ]:
vertical_concat

        Alpha       Delta       Beta     Gamma    Label
0   21.582478   75.814406   9.235991  0.708799    Focus
1    1.173516    5.487767   1.075237  0.142068    Focus
2    1.795885   31.367239   0.837457  0.117887    Focus
3   18.083213   52.505458   7.819185  0.777453    Focus
4   44.822451  191.980194  17.116479  1.270734    Focus
5    1.469471    8.405305   1.815163  0.190643    Focus
6    3.766179   15.596748   2.091129  0.266263    Focus
7   21.582478   75.814406   9.235991  0.708799    Focus
8    1.173516    5.487767   1.075237  0.142068    Focus
9    1.795885   31.367239   0.837457  0.117887    Focus
10  18.083213   52.505458   7.819185  0.777453    Focus
11  44.822451  191.980194  17.116479  1.270734    Focus
12   1.469471    8.405305   1.815163  0.190643    Focus
13   3.766179   15.596748   2.091129  0.266263    Focus
14   1.313192    1.292633   0.482070  0.068316    Focus
15   1.940559    3.203893   0.654321  0.087033    Focus
16   3.374943    8.030812   0.768921  0.082389    Focus
17   2.366213    9.560376   0.635911  0.122696    Focus
18   2.684648   16.140514   0.767892  0.104459    Focus
19   2.274508    5.442220   0.643466  0.119283    Focus
20   2.736497    2.579588   0.553741  0.064100    Focus
21   4.758651   23.865132   0.603753  0.096275  Unfocus
22   1.546638    1.009209   0.324108  0.033231  Unfocus
23   3.106714    4.062598   0.597593  0.061847  Unfocus
24   4.157316    7.888724   0.622376  0.075872  Unfocus
25   3.640760    2.592613   0.456683  0.062091  Unfocus
26   3.962184    2.158681   0.569189  0.094259  Unfocus
27   1.173528    1.251538   0.352267  0.048891  Unfocus
28   1.569356   37.062861   0.549699  0.107984  Unfocus
29   2.085261   19.195052   0.519313  0.117127  Unfocus
30   0.882999   21.597552   0.404765  0.095855  Unfocus
31   2.086651   59.156010   0.643488  0.132323  Unfocus
32   2.121281   43.761955   0.630762  0.102340  Unfocus
33   2.002300   19.057509   0.688112  0.122486  Unfocus
34   1.527285   12.060401   0.627175  0.093167  Unfocus
35   2.018304    3.548523   0.496081  0.088527  Unfocus
36   2.900375    5.391830   0.454510  0.092746  Unfocus
37   2.140496    8.453167   0.628486  0.059200  Unfocus
38   2.329915    9.603010   0.766771  0.089855  Unfocus
39   2.345177   16.863827   0.839385  0.094189  Unfocus
40   3.134618    6.598900   0.546060  0.106409  Unfocus
41   2.525461    2.779900   0.382307  0.084817  Unfocus

In [ ]:
vertical_concat.to_csv('/content/drive/MyDrive/NewCVStoPart-IIIMarch1/NewCSVMarch1_Dataset_II_BandstoPart-IIITrain.csv', index = False)

In [ ]:
# vertical_concat2 = pd.concat([dfrowslistFocus1,dfrowslistFocus2, dfrowslistFocus3, dfrowslistUnfocus1,dfrowslistUnfocus2, dfrowslistUnfocus3], axis=0, ignore_index=True)

In [ ]:
vertical_concat2 = pd.concat([dfrowslistFocus4, dfrowslistFocus5, dfrowslistUnfocus4, dfrowslistUnfocus5], axis=0, ignore_index=True)
vertical_concat2.drop(columns = 'channel', inplace = True) # equivanent to vertical_concat = assignment
vertical_concat2 = vertical_concat.rename(columns = {'alpha':'Alpha', 'delta':'Delta', 'beta':'Beta','gamma':'Gamma','state':'Label'})
vertical_concat2.to_csv('/content/drive/MyDrive/NewCVStoPart-IIIMarch1/NewCSVMarch1_Dataset_II_BandstoPart-IIITest.csv', index = False)

In [ ]:
dfrowslistFocus = dfrowslistFocus.rename(columns = {'alpha':'Alpha', 'delta':'Delta', 'beta':'Beta','gamma':'Gamma','state':'Label'})

In [ ]:
dfrowslistFocus.drop(columns = ['channel'])

      Alpha      Delta      Beta     Gamma  Label
0  5.125695   5.224368  1.025285  0.151677  Focus
1  4.157976   8.158955  0.919970  0.089221  Focus
2  3.873814  19.802450  1.273993  0.174228  Focus
3  5.810522  12.872709  1.094797  0.180937  Focus
4  2.862118   5.320820  0.844567  0.101251  Focus
5  2.707624   9.567089  1.008565  0.162737  Focus
6  4.379317   5.310511  0.993807  0.143346  Focus

In [ ]:
dfrowslistUnfocus = dfrowslistUnfocus.drop(columns = ['channel'])

KeyError: ignored

In [ ]:
dfrowslistUnfocus = dfrowslistFocus.rename(columns = {'alpha':'Alpha', 'delta':'Delta', 'beta':'Beta','gamma':'Gamma','state':'Label'})

In [ ]:
dfrowslistUnfocus

      Alpha      Delta      Beta     Gamma  Label channel
0  5.125695   5.224368  1.025285  0.151677  Focus      F7
1  4.157976   8.158955  0.919970  0.089221  Focus      F3
2  3.873814  19.802450  1.273993  0.174228  Focus      P7
3  5.810522  12.872709  1.094797  0.180937  Focus      O1
4  2.862118   5.320820  0.844567  0.101251  Focus      O2
5  2.707624   9.567089  1.008565  0.162737  Focus      P8
6  4.379317   5.310511  0.993807  0.143346  Focus     AF4

In [ ]:
vertical_concat = pd.concat([dfrowslistFocus, dfrowslistUnfocus], axis=0)

In [ ]:
vertical_concat.reset_index(drop=True)
# vertical_concat.drop(columns='index')

       Alpha      Delta      Beta     Gamma  Label channel
0   5.125695   5.224368  1.025285  0.151677  Focus      F7
1   4.157976   8.158955  0.919970  0.089221  Focus      F3
2   3.873814  19.802450  1.273993  0.174228  Focus      P7
3   5.810522  12.872709  1.094797  0.180937  Focus      O1
4   2.862118   5.320820  0.844567  0.101251  Focus      O2
5   2.707624   9.567089  1.008565  0.162737  Focus      P8
6   4.379317   5.310511  0.993807  0.143346  Focus     AF4
7   5.125695   5.224368  1.025285  0.151677  Focus      F7
8   4.157976   8.158955  0.919970  0.089221  Focus      F3
9   3.873814  19.802450  1.273993  0.174228  Focus      P7
10  5.810522  12.872709  1.094797  0.180937  Focus      O1
11  2.862118   5.320820  0.844567  0.101251  Focus      O2
12  2.707624   9.567089  1.008565  0.162737  Focus      P8
13  4.379317   5.310511  0.993807  0.143346  Focus     AF4

In [ ]:
vertical_concat.drop(columns='channel')

      Alpha      Delta      Beta     Gamma  Label
0  5.125695   5.224368  1.025285  0.151677  Focus
1  4.157976   8.158955  0.919970  0.089221  Focus
2  3.873814  19.802450  1.273993  0.174228  Focus
3  5.810522  12.872709  1.094797  0.180937  Focus
4  2.862118   5.320820  0.844567  0.101251  Focus
5  2.707624   9.567089  1.008565  0.162737  Focus
6  4.379317   5.310511  0.993807  0.143346  Focus
0  5.125695   5.224368  1.025285  0.151677  Focus
1  4.157976   8.158955  0.919970  0.089221  Focus
2  3.873814  19.802450  1.273993  0.174228  Focus
3  5.810522  12.872709  1.094797  0.180937  Focus
4  2.862118   5.320820  0.844567  0.101251  Focus
5  2.707624   9.567089  1.008565  0.162737  Focus
6  4.379317   5.310511  0.993807  0.143346  Focus

In [ ]:
# dfrowslistFocus.to_csv('/content/drive/MyDrive/NewCSVs_Dataset_I_BandstoPart-III')

In [ ]:
# dToBands1 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter1.csv')
# dToBands2 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter2.csv')
# dToBands3 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter3.csv')
# dToBands4 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter4.csv')
# dToBands5 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/dfilter5.csv')

In [ ]:
bands = {'theta': (4, 8), 'alpha': (8, 13), 'delta': (0.5, 4), 'beta': (13, 30), 'gamma': (30, np.inf)}
bands.items()

dict_items([('theta', (4, 8)), ('alpha', (8, 13)), ('delta', (0.5, 4)), ('beta', (13, 30)), ('gamma', (30, inf))])

In [ ]:
# def get_powers(channel, sf=128):
#     channel = channel - channel.mean()
#     freq, psd = signal.periodogram(channel, fs=sf, nfft=256)

#     powers = {}
#     for band_name, band_limits in bands.items():
#         low, high = band_limits
#         powers[band_name] = psd[(freq >= low) & (freq < high)].mean().real
#     return powers

In [ ]:
dfPower10 = dToBands10.drop(columns = 'target')
# dfPower2 = dToBands2.drop(columns = 'target')
# dfPower3 = dToBands3.drop(columns = 'target')
# dfPower4 = dToBands4.drop(columns = 'target')
# dfPower5 = dToBands5.drop(columns = 'target')

In [ ]:
# del dfPower10['Unnamed: 0']
dfPower10
# useful_channels = ['F7','F3','P7','O1','O2','P8','AF4','target'] #(8 elements )

         F7         F3         P7        O1        O2         P8        AF4
0 -1.256006  -1.688765  -2.046898 -1.449457 -0.982337  -2.106340  -3.323160
1  1.805012  -0.656932   3.377382 -0.997785  2.531933  -1.177855   0.663618
2  2.230748  -1.034433   3.551931 -2.198781  3.348797   3.165657  -0.952302
3  2.072593  -2.175822  -0.042707 -2.501437  3.881218   3.887775  -5.784138
4  0.274439  -3.461580   0.734968 -0.303572  4.212697  -0.413768  -9.905159
5 -3.387096  -5.281154   6.829504  1.623639  1.841961  -3.269057 -12.949960
6 -3.281422  -8.346757   8.168389  0.931090 -0.683911  -6.192406 -15.917048
7 -0.558461 -10.945775   4.491370 -1.377585 -1.044500 -11.121062 -16.389522
8 -2.076100  -8.389466   7.606028 -3.822472 -2.380325  -9.941170  -8.968418
9 -5.595584  -3.500649  13.985911 -6.355213 -5.010044  -2.365027   0.602396

In [ ]:
def get_powers(channel, sf=128):
    channel = channel - channel.mean()
    freq, psd = signal.periodogram(channel, fs=sf, nfft=256)

    powers = {}
    for band_name, band_limits in bands.items():
        low, high = band_limits
        powers[band_name] = psd[(freq >= low) & (freq < high)].mean().real
    return powers

In [ ]:
states10 = dfPower10.to_dict() 

# dfPower1 = dfilter1.drop(columns = 'target')
# states2 = dfPower2.to_dict()
# states3 = dfPower3.to_dict()
# states4 = dfPower4.to_dict()
# states5 = dfPower5.to_dict()

In [ ]:
#backup codes in case
# states = {col: dfToPowers[col].to_dict() for col in dfToPowers}
# print(states)
# states = dfToPowers.to_dict(orient='records')
# states = [dict(zip(dfToPowers.columns, row)) for row in dfToPowers.itertuples(index=False)]


# Set the first column as the index
# df5 = df4.set_index('target')

# Convert the dataframe into a dictionary
# states = df5.T.to_dict('list')
# states = {col: df4[col].to_dict(orient='list') for col in df4}
# states = df4.set_index('target').T.to_dict('list')
# states.items()

In [ ]:
states10

{'F7': {0: -1.2560062260395188,
  1: 1.8050116884835357,
  2: 2.230747748587424,
  3: 2.072592769133508,
  4: 0.2744389150785071,
  5: -3.387095796170951,
  6: -3.281422453634512,
  7: -0.5584606809016486,
  8: -2.0760995309007404,
  9: -5.595584230496132},
 'F3': {0: -1.6887653963825322,
  1: -0.6569317509873027,
  2: -1.03443270666344,
  3: -2.175822088256208,
  4: -3.4615796341251728,
  5: -5.281154441289818,
  6: -8.346756719877233,
  7: -10.945774583535613,
  8: -8.389465769126144,
  9: -3.50064891985633},
 'P7': {0: -2.0468981939597324,
  1: 3.3773821409507025,
  2: 3.551931260923067,
  3: -0.0427067160231263,
  4: 0.734967883908622,
  5: 6.829504064746183,
  6: 8.168388803360733,
  7: 4.491370035697807,
  8: 7.606027702859973,
  9: 13.98591114092701},
 'O1': {0: -1.4494572105635388,
  1: -0.9977851884028964,
  2: -2.1987805522996977,
  3: -2.5014370455254467,
  4: -0.3035721640640014,
  5: 1.6236386374149865,
  6: 0.9310900441034784,
  7: -1.3775849994851683,
  8: -3.822471929186549,
  9: -6.355213396206391},
 'O2': {0: -0.9823368087433142,
  1: 2.531933295783848,
  2: 3.3487972781514053,
  3: 3.881217647269896,
  4: 4.212697012993396,
  5: 1.841960903793037,
  6: -0.6839113015356479,
  7: -1.0444999667531147,
  8: -2.3803248039953986,
  9: -5.010043536342354},
 'P8': {0: -2.1063404374795143,
  1: -1.1778553252251056,
  2: 3.1656569245196966,
  3: 3.887775254111899,
  4: -0.4137681277569287,
  5: -3.269057293218283,
  6: -6.192406016768524,
  7: -11.121061764291923,
  8: -9.941169647450192,
  9: -2.3650271940708203},
 'AF4': {0: -3.323159863276544,
  1: 0.6636175309330481,
  2: -0.9523015506992158,
  3: -5.78413785608715,
  4: -9.905159351808171,
  5: -12.949960046271924,
  6: -15.917048399580658,
  7: -16.389521576930733,
  8: -8.968417983833582,
  9: 0.6023958237826399}}

In [ ]:
len(states10
    )

7

In [ ]:
states10.items()

In [ ]:
L1 = []
L2 = []
L3=[]

In [ ]:
channel_range = np.array(range(0, 7))
channel_list = ['F7','F3','P7','O1','O2','P8','AF4'] #(7chs)
channel_mymap = dict(zip(channel_list, channel_range))

In [ ]:
channel_mymap.items()

dict_items([('F7', 0), ('F3', 1), ('P7', 2), ('O1', 3), ('O2', 4), ('P8', 5), ('AF4', 6)])

In [ ]:
# Step 5: Separate 5 df's for each person and save on each step.
listOfRows = []
# states = get_data(f"eeg_record{subject_idx}.mat")
def powers(states):
  for ch_name, ch_idx in channel_mymap.items():
      for state, eeg in states.items():
          print(eeg)

          powers = get_powers(eeg[:, ch_idx])
          powers['state'] = state # Channel
          powers['channel'] = ch_name
          # powers['subject'] = f"subject_{subject_idx}"
          listOfRows.append(powers)
  return listOfRows

In [ ]:
np.array(eeg)[:,range(0,7)]

In [ ]:
states10

In [ ]:
type(states10)

dict

In [ ]:
type(d)

dict

In [ ]:
d.items()

In [ ]:
import pandas as pd
dfbands = pd.DataFrame(listOfRows1)

In [ ]:
dfrowslist = pd.DataFrame.from_dict(powers(states10))
dfrowslist = dfrowslist.rename(columns = {'alpha':'Alpha', 'delta':'Delta', 'beta':'Beta','gamma':'Gamma','state':'Label'})
dfNew = dfrowslist.drop_duplicates()
dftoCSVADHD_DS_I.to_csv('/content/drive/MyDrive/NewCsvs/dftoCSVADHD.csv')

In [ ]:
df5.to_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/States.csv')

In [ ]:
df5 = pd.read_csv('/content/drive/MyDrive/dfICAFiltered Dataset-II/States.csv')

In [ ]:
get_powers(np.array(df5.drop(['7'], axis = 1)))
# df_full2= df_full2.drop(['Unnamed: 0', 'channel','Channel'], axis =1)

In [ ]:

# # dfStates = pd.DataFrame.from_dict(states, index=0)
# dfStates = pd.DataFrame.from_dict(list(states))
# dfStates